print("Hello World, I say 'Hello' ")
print(100)
print(100+44)
print("100+44")
print('sdf')
print('Hello' + 'Chetan')
print('Hello ' + 'Chetan')
print("Hello, My name is \"Chetan\"") # '\' to put actual double quote.
print("This is one line \n This is another line")
print("This is third line")
print("\tThis is example of tab")
print("This sign \\ is backslash")
input('Tell me your name: ')
print("Your name is " + input("Tell me your first name: ") + " " + input("Tell me your last name: "))
print(' ' ' sdfsdf' "dsfsd k")